### PR TITLE
create system block and setrw on it

### PR DESCRIPTION
**Pull request by HuskyDG**
```
$ grep " / " /proc/mounts
/dev/root
$ blockdev --setrw $(grep -E "/dev/block.* / " /proc/mounts | cut -f 1 -d ' ' )
(nothing)
$
```
and cause:

```
- Adding addon.d survival script
! Installation failed
```

### CODE REVIEW

**Comment by binarynoise** [comment]
Would you please add the full contents of `/proc/mounts` and the full output of `mount` (or at least the lines without magisk mounts)?

**Comment by HuskyDG** [comment]
> Would you please add the full contents of `/proc/mounts` and the full output of `mount` (or at least the lines without magisk mounts)?

[mounts.txt](https://github.com/programminghoch10/Lygisk/files/9389549/mounts.txt)

**Comment by HuskyDG** [comment]
Screenshot_20220822-020157_Lygisk

**Comment by HuskyDG** [comment]
@programminghoch10 @Linux4 @binarynoise 
Magisk always unlocks all partitions after reboot, so just simply remove `blockdev --setrw system_block` will fix

**Pull request closed without merging**
